### ISSUE TITLE
Application crashing on start up.

### ISSUE THREAD

**Issue by bertokhoury** [bertokhoury/ChatBot#5]
`06-11 13:28:18.874 5752-5752/? I/art: Not late-enabling -Xcheck:jni (already on)
06-11 13:28:18.874 5752-5752/? W/art: Unexpected CPU variant for X86 using defaults: x86
06-11 13:28:18.917 5752-5752/com.example.albertkhoury.chatbotsofwerx D/AndroidRuntime: Shutting down VM
06-11 13:28:18.917 5752-5752/com.example.albertkhoury.chatbotsofwerx E/AndroidRuntime: FATAL EXCEPTION: main`

I have tried changing up the target API and also have made sure all `findViewById` declarations are not outside of the `onCreate` . I am sure this is a simple issue that will be closed very quick.

**Comment by bertokhoury** [comment]
This is due to needing an `onCreateOptionsMenu` to implement the `SearchView` Widget

**Comment by bertokhoury** [comment]
Here is the Logcat:


06-11 14:37:33.787 4060-4060/? E/libprocessgroup: failed to make and chown /acct/uid_10059: Read-only file system
06-11 14:37:33.787 4060-4060/? W/Zygote: createProcessGroup failed, kernel missing CONFIG_CGROUP_CPUACCT?
06-11 14:37:33.788 4060-4060/? I/art: Not late-enabling -Xcheck:jni (already on)
06-11 14:37:33.842 4060-4060/com.example.albertkhoury.chatbotsofwerx D/AndroidRuntime: Shutting down VM
06-11 14:37:33.845 4060-4060/com.example.albertkhoury.chatbotsofwerx E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.albertkhoury.chatbotsofwerx, PID: 4060
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.albertkhoury.chatbotsofwerx/com.example.albertkhoury.chatbotsofwerx.MainActivity}: android.view.InflateException: Binary XML file line #31: Error inflating class android.support.v7.widget.SearchView.SearchAutoComplete
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
        at android.app.ActivityThread.access$800(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: android.view.InflateException: Binary XML file line #31: Error inflating class android.support.v7.widget.SearchView.SearchAutoComplete
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:757)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
        at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:378)
        at android.app.Activity.setContentView(Activity.java:2145)
        at com.example.albertkhoury.chatbotsofwerx.MainActivity.onCreate(MainActivity.java:44)
        at android.app.Activity.performCreate(Activity.java:5990)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
        at android.app.ActivityThread.access$800(ActivityThread.java:151) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5254) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v7.widget.SearchView.SearchAutoComplete" on path: DexPathList[[zip file "/data/app/com.example.albertkhoury.chatbotsofwerx-2/base.apk"],nativeLibraryDirectories=[/data/app/com.example.albertkhoury.chatbotsofwerx-2/lib/x86, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at android.view.LayoutInflater.createView(LayoutInflater.java:571)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
        at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:378) 
        at android.app.Activity.setContentView(Activity.java:2145) 
        at com.example.albertkhoury.chatbotsofwerx.MainActivity.onCreate(MainActivity.java:44) 
        at android.app.Activity.performCreate(Activity.java:5990) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
        at android.app.ActivityThread.access$800(ActivityThread.java:151) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5254) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
    	Suppressed: java.lang.ClassNotFoundException: android.support.v7.widget.SearchView.SearchAutoComplete
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 25 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
06-11 14:37:37.382 4060-4060/? I/Process: Sending signal. PID: 4060 SIG: 9

**Comment by bertokhoury** [comment]
Here is the Logcat: 


`06-11 14:37:33.787 4060-4060/? E/libprocessgroup: failed to make and chown /acct/uid_10059: Read-only file system
06-11 14:37:33.787 4060-4060/? W/Zygote: createProcessGroup failed, kernel missing CONFIG_CGROUP_CPUACCT?
06-11 14:37:33.788 4060-4060/? I/art: Not late-enabling -Xcheck:jni (already on)
06-11 14:37:33.842 4060-4060/com.example.albertkhoury.chatbotsofwerx D/AndroidRuntime: Shutting down VM
06-11 14:37:33.845 4060-4060/com.example.albertkhoury.chatbotsofwerx E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.albertkhoury.chatbotsofwerx, PID: 4060
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.albertkhoury.chatbotsofwerx/com.example.albertkhoury.chatbotsofwerx.MainActivity}: android.view.InflateException: Binary XML file line #31: Error inflating class android.support.v7.widget.SearchView.SearchAutoComplete`

**Comment by bertokhoury** [comment]
Here is the Logcat : 

06-11 14:37:33.787 4060-4060/? E/libprocessgroup: failed to make and chown /acct/uid_10059: Read-only file system

06-11 14:37:33.787 4060-4060/? W/Zygote: createProcessGroup failed, kernel missing CONFIG_CGROUP_CPUACCT?

06-11 14:37:33.788 4060-4060/? I/art: Not late-enabling -Xcheck:jni (already on)

06-11 14:37:33.842 4060-4060/com.example.albertkhoury.chatbotsofwerx D/AndroidRuntime: Shutting down VM

06-11 14:37:33.845 4060-4060/com.example.albertkhoury.chatbotsofwerx E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.albertkhoury.chatbotsofwerx, PID: 4060
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.albertkhoury.chatbotsofwerx/com.example.albertkhoury.chatbotsofwerx.MainActivity}: android.view.InflateException: Binary XML file line #31: Error inflating class android.support.v7.widget.SearchView.SearchAutoComplete

**Comment by bertokhoury** [comment]
Problem was regarding the Manifest file
